### ISSUE TITLE
ConsoleCaptor#clearOutput doesn't reset System.out and System.err

### ISSUE THREAD

**Issue by charphi** [Hakky54/console-captor#1]
**Describe the bug**
The method `ConsoleCaptor#clearOutput` creates new streams but doesn't register them to `System.out` and `System.err`.
So subsequent calls to `#getStandardOutput()` and `#getErrorOutput()` always return empty lists.

**To Reproduce**
```java
try (ConsoleCaptor console = new ConsoleCaptor()) {
    System.out.println("hello");
    // ok
    assertThat(console.getStandardOutput()).containsExactly("hello");

    console.clearOutput();

    System.out.println("world");
    // ko
    assertThat(console.getStandardOutput()).containsExactly("world");
}
```

**Comment by Hakky54** [comment]
> My only concern is that it might not work on parallel tests but I don't see a solution giving the way the JDK API is designed.

I am pretty limited to the capabilities of the System.out and System.err functions as the library depends on them so not quite sure if this library will work with parallel tests. I haven't tried it out yet, but maybe it will work
