### ISSUE TITLE
getStandardOutput() not returning anything

### ISSUE THREAD

**Issue by tiannahomer** [Hakky54/console-captor#3]
Hello,

I am trying to use ConsoleCaptor to get logs from the console. I tried using LogCaptor, but it doesn't seem to work with my Maven repositories, so I resorted to ConsoleCaptor since it seems quick and easy to set up!

Background
I have a class that uses SL4J logging binded to a Log4J2 configuration. I have set up my `log4j2.xml` file with a Console Appender that logs error messages to the console. I know this works, because when I run the unit tests, I can see the log message printed in the console. I think the issue I am experiencing is ConsoleCaptor not picking up the log message from the console, because when I do a `System.out.println(consoleCaptor.getStandardOutput())`, nothing is returned. 

My pom.xml file has the following dependencies:
```
<dependencies>
        <dependency>
            <groupId>io.github.hakky54</groupId>
            <artifactId>consolecaptor</artifactId>
            <version>1.0.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j18-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.0-alpha7</version>
        </dependency>
```

In my test file, I have set up ConsoleCaptor as follows:
```
@BeforeAll
    public static void setupConsoleCaptor() {
        consoleCaptor = new ConsoleCaptor();
    }

    @AfterEach
    public void clearOutput() {
        consoleCaptor.clearOutput();
    }

    @AfterAll
    public static void tearDown() {
        consoleCaptor.close();
    }
```

Do you have any idea what I might be missing or doing wrong?

**Comment by Hakky54** [comment]
Hi @tiannahomer  can you add the following file in the test resources:  **log4j2.xml**

With the following content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="INFO">
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n" />
        </Console>
    </Appenders>
    <Loggers>
        <Root level="debug">
            <AppenderRef ref="Console" />
        </Root>
    </Loggers>
</Configuration>
```

The above configuration will append all of your logs to the console and console captor will then be able to capture those logs. Can you try it and share your results?
